import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://www.z-pdf.com/themes/default/resources/css/bootstrap.min.css" />
        {/* <link rel="stylesheet" href="https://www.z-pdf.com/themes/default/resources/css/plugins.css" /> */}
        <link rel="stylesheet" href="https://www.z-pdf.com/themes/default/resources/css/style.css" />

      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
